version: '3'
services:
  db:
    build: ./db
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
  web:
    build: ./web
    ports:
      - '80:80'
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
       - 8080:80
    volumes:
       - /sessions
    depends_on:
      - db
      - web
